# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import post.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lfcat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresaDeFacturare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('nrdetelefon', models.CharField(max_length=10)),
                ('adresa', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=50)),
                ('localitate', models.CharField(max_length=50)),
                ('codpostal', models.CharField(max_length=50)),
                ('tva', models.BooleanField(default=True)),
                ('nume2', models.CharField(max_length=50, null=True)),
                ('prenume2', models.CharField(max_length=50, null=True)),
                ('adresa2', models.CharField(max_length=100, null=True)),
                ('judet2', models.CharField(max_length=50, null=True)),
                ('localitate2', models.CharField(max_length=50, null=True)),
                ('codpostal2', models.CharField(max_length=50, null=True)),
                ('comentarii', models.CharField(max_length=1000, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detinator', to=settings.AUTH_USER_MODEL)),
                ('posesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('is_parent', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='CosulMeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('price', models.CharField(max_length=15)),
                ('season', models.IntegerField(choices=[(0, 'Primavara'), (1, 'Vara'), (2, 'Toamna'), (3, 'Iarna')])),
                ('um', models.IntegerField(choices=[(0, 'Kilogram'), (1, 'Bucata')])),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('legfruccategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfcat.Products')),
                ('lfcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfcat.Lfcategory')),
            ],
        ),
        migrations.AddField(
            model_name='cosulmeu',
            name='anunturi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cos_comandaa', to='post.PostModel'),
        ),
        migrations.AddField(
            model_name='cosulmeu',
            name='cumparator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cos_cumparator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cosulmeu',
            name='vanzator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cos_vanzator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.PostModel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='comenzi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comanda', to='post.PostModel'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='cumparator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comanda_cumparator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='vanzator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comanda_vanzator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adresadefacturare',
            name='postcomanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comanda', to='post.PostModel'),
        ),
    ]
