# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-21 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import post.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lfcat', '__first__'),
        ('categorie', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('is_parent', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='CosulMeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('cantity', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('price', models.CharField(max_length=15)),
                ('delivery_time', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('lfcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfcat.Lfcategory')),
            ],
        ),
        migrations.AddField(
            model_name='cosulmeu',
            name='anunturi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cos', to='post.PostModel'),
        ),
        migrations.AddField(
            model_name='cosulmeu',
            name='cumparator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cos_cumparator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cosulmeu',
            name='vanzator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cos_vanzator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.PostModel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
