# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
