# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lfcat', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='lfcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfcat.Lfcategory'),
        ),
    ]
