# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postmodel_lfcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
