# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-21 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180221_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='date',
        ),
    ]
