# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-21 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('alegator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorit', to=settings.AUTH_USER_MODEL)),
                ('ales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=1000)),
                ('titlu', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesaje', to=settings.AUTH_USER_MODEL)),
                ('destinatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesajee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produs1', models.CharField(max_length=30)),
                ('produs2', models.CharField(max_length=30)),
                ('produs3', models.CharField(max_length=30)),
                ('produs4', models.CharField(max_length=30)),
                ('produs5', models.CharField(max_length=30)),
                ('descriere', models.CharField(max_length=1000)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_location)),
                ('userul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesajj', models.CharField(max_length=1000)),
                ('titluu', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
                ('destinatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
