# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_profile.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=1000)),
                ('titlu', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('produs1', models.CharField(max_length=30)),
                ('produs2', models.CharField(max_length=30)),
                ('produs3', models.CharField(max_length=30)),
                ('produs4', models.CharField(max_length=30)),
                ('produs5', models.CharField(max_length=30)),
                ('descriere', models.CharField(max_length=1000)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesajj', models.CharField(max_length=1000)),
                ('titluu', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
                ('destinatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mesaje',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesaje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesaje',
            name='destinatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesajee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorit',
            name='alegator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorit',
            name='ales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritt', to=settings.AUTH_USER_MODEL),
        ),
    ]
