# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaje',
            name='titlu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
