# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AlterField(
            model_name='account2',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, null=True, unique=True),
        ),
    ]
