# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-12 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account2_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account2',
            name='approve',
        ),
    ]
