# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-12 13:54
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_account2_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account2',
            name='file1',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_location),
        ),
        migrations.AlterField(
            model_name='account2',
            name='file2',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_location),
        ),
        migrations.AlterField(
            model_name='account2',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
