language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - cd info && yes | python manage.py makemigrations && yes | python manage.py migrate  && python manage.py test